##\u670D\u52A1\u5668\u914D\u7F6E
server:
  port: 8090

##\u6570\u636E\u6E90\u914D\u7F6E

spring:
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-while-idle: true
      validation-query: SELECT 1
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./project.sqlite
#\u6574\u5408mybatis

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #\u58F0\u660EMybatis\u6620\u5C04\u6587\u4EF6\u6240\u5728\u7684\u4F4D\u7F6E
